CREATE TABLE COURSES (
    "COURSE_ID" INTEGER NOT NULL PRIMARY KEY,
    "COURSE_NAME" VARCHAR(200),
    "CREDITS" INTEGER);
CREATE TABLE "ENROLLMENTS" (
	"ENROLLMENT_ID"	INTEGER,
	"STUDENT_ID"	INTEGER,
	"COURSE_ID"	INTEGER,
	"GRADE"	TEXT,
	PRIMARY KEY("ENROLLMENT_ID"),
	FOREIGN KEY("COURSE_ID") REFERENCES "COURSES"("COURSE_ID"),
	FOREIGN KEY("STUDENT_ID") REFERENCES "STUDENT"("STUDENT_ID")
);s
CREATE TABLE "STUDENT" (
	"STUDENT_ID"	INTEGER NOT NULL,
	"NAME"	VARCHAR(250),
	"AGE"	INTEGER,
	"GENDER"	VARCHAR(10),
	PRIMARY KEY("STUDENT_ID")
);